[project]
name = "compsproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dash>=2.18.0",
    "pandas>=2.2.2",
]
